ci:
  autoupdate_schedule: quarterly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
    # Current docformatter version has a problem with urls (it's annoying)
# -   repo: https://github.com/PyCQA/docformatter
#     rev: v1.6.0.rc1
#     hooks:
#     -   id: docformatter
#         args: [--in-place, --make-summary-multi-line, --pre-summary-newline]
-   repo: https://github.com/keewis/blackdoc
    rev: v0.4.1
    hooks:
    -   id: blackdoc
        additional_dependencies: ['black==24.8.0']
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    -   id: codespell
        types_or: [python, rst, markdown]
        files: ^(linopy|doc)/
-   repo: https://github.com/aflc/pre-commit-jupyter
    rev: v1.2.1
    hooks:
    -   id: jupyter-notebook-cleanup
        exclude: examples/solve-on-remote.ipynb
