repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
    # Current docformatter version has a problem with urls (it's annoying)
# -   repo: https://github.com/PyCQA/docformatter
#     rev: v1.6.0.rc1
#     hooks:
#     -   id: docformatter
#         args: [--in-place, --make-summary-multi-line, --pre-summary-newline]
-   repo: https://github.com/keewis/blackdoc
    rev: v0.3.8
    hooks:
      - id: blackdoc
-   repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
    -   id: absolufy-imports
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
    -   id: codespell
        types_or: [python, rst, markdown]
        files: ^(linopy|doc)/
-   repo: https://github.com/aflc/pre-commit-jupyter
    rev: v1.2.1
    hooks:
    -   id: jupyter-notebook-cleanup
        exclude: examples/solve-on-remote.ipynb
